---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/profiles":
    get:
      summary: list profiles
      responses:
        '200':
          description: successful
    post:
      summary: create profile
      responses:
        '200':
          description: successful
  "/profiles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show profile
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
