---
openapi: 3.0.1
info:
  title: PROFILE API
  version: v1
paths:
  "/profiles":
    get:
      summary: list profiles
      responses:
        '200':
          description: successful
    post:
      summary: create profile
      parameters: []
      responses:
        '201':
          description: profile created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                profile:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    birthdate:
                      type: string
                      format: date
                    phone:
                      type: string
                    links:
                      type: array
                      items:
                        type: string
                    role:
                      type: string
                    bio:
                      type: string
                    experiences_attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          company_name:
                            type: string
                          start_date:
                            type: string
                            format: date
                          end_date:
                            type: string
                            format: date
                          function_performed:
                            type: string
                        required:
                        - title
                        - company_name
                        - start_date
                        - end_date
                        - function_performed
                    studies_attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          start_date:
                            type: string
                            format: date
                          end_date:
                            type: string
                            format: date
                        required:
                        - title
                        - start_date
                        - end_date
                    ability_ids:
                      type: array
                      items:
                        type: integer
                    tech_ids:
                      type: array
                      items:
                        type: integer
                  required:
                  - name
                  - email
                  - birthdate
                  - phone
                  - role
              required:
              - profile
  "/profiles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show profile
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
