---
openapi: 3.0.1
info:
  title: PROFILE API
  version: v1
paths:
  "/health":
    get:
      summary: Health check
      tags:
      - Health
      responses:
        '200':
          description: Health check
          content:
            application/json:
              examples:
                example:
                  value:
                    status: UP
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: UP
  "/profiles":
    get:
      summary: list profiles
      tags:
      - - Profiles
      responses:
        '200':
          description: successful
    post:
      summary: create profile
      tags:
      - - Profiles
      parameters: []
      responses:
        '201':
          description: profile created
          content:
            application/json:
              examples:
                created:
                  value:
                    id: 12
                    name: Sabrina
                    email: sabrina@example.com
                    birthdate: '1991-07-27'
                    phone: '85988556677'
                    links: []
                    role: fullstack
                    created_at: '2023-09-15T05:00:49.347Z'
                    updated_at: '2023-09-15T05:00:49.347Z'
                    bio: Uma desenvolvedora fullstack que atualmente está se dedicando
                      a Ruby on Rails, feliz com a ideia de ser fullstack
                    city_id: 678
                    experiences:
                    - id: 13
                      title: Desenvolvedor Web Fullstack
                      company_name: TechCo
                      start_date: '2021-03-01'
                      end_date: 'null'
                      function_performed: Desenvolver Rails atuando na concepção de
                        projetos
                      profile_id: 12
                      created_at: '2023-09-15T05:00:49.349Z'
                      updated_at: '2023-09-15T05:00:49.349Z'
                    - id: 14
                      title: Estagiário de Desenvolvimento Web
                      company_name: WebTech
                      start_date: '2020-01-15'
                      end_date: '2020-12-31'
                      function_performed: Desenvolver com React
                      profile_id: 12
                      created_at: '2023-09-15T05:00:49.351Z'
                      updated_at: '2023-09-15T05:00:49.351Z'
                    studies:
                    - id: 'null'
                      title: Bacharelado em Ciência da Computação
                      start_date: '2018-09-01'
                      end_date: '2022-06-30'
                      profile_id: 12
                      created_at: 'null'
                      updated_at: 'null'
                      link: 'null'
                      institution: 'null'
                    - id: 'null'
                      title: Curso de Desenvolvimento Web Avançado
                      start_date: 'null'
                      end_date: 'null'
                      profile_id: 12
                      created_at: 'null'
                      updated_at: 'null'
                      link: 'null'
                      institution: 'null'
                    abilities:
                    - id: 1
                      name: Design de Interface de Usuário (UI)
                      role: frontend
                      created_at: '2023-09-15T04:46:58.944Z'
                      updated_at: '2023-09-15T04:46:58.944Z'
                      description: Habilidade em criar interfaces de usuário atraentes
                        e funcionais.
                    - id: 3
                      name: Design de Experiência do Usuário (UX)
                      role: frontend
                      created_at: '2023-09-15T04:46:58.954Z'
                      updated_at: '2023-09-15T04:46:58.954Z'
                      description: Conhecimento em criar experiências de usuário intuitivas
                        e eficientes.
                    softskills:
                    - id: 1
                      name: Comunicação
                      created_at: '2023-09-15T04:46:59.465Z'
                      updated_at: '2023-09-15T04:46:59.465Z'
                    - id: 2
                      name: Trabalho em Equipe
                      created_at: '2023-09-15T04:46:59.472Z'
                      updated_at: '2023-09-15T04:46:59.472Z'
                    - id: 3
                      name: Adaptabilidade
                      created_at: '2023-09-15T04:46:59.477Z'
                      updated_at: '2023-09-15T04:46:59.477Z'
                    techs:
                    - id: 3
                      name: Node.js
                      created_at: '2023-09-15T04:46:58.573Z'
                      updated_at: '2023-09-15T04:46:58.573Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                profile:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    birthdate:
                      type: string
                      format: date
                    bio:
                      type: string
                    phone:
                      type: string
                    links:
                      type: array
                      items:
                        type: string
                    role:
                      type: string
                    experiences_attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          company_name:
                            type: string
                          start_date:
                            type: string
                            format: date
                          end_date:
                            type: string
                            format: date
                          function_performed:
                            type: string
                        required:
                        - title
                        - company_name
                        - start_date
                        - function_performed
                    studies_attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          institution:
                            type: string
                          start_date:
                            type: string
                            format: date
                          end_date:
                            type: string
                            format: date
                          link:
                            type: string
                        required:
                        - title
                        - institution
                    ability_ids:
                      type: array
                      items:
                        type: integer
                    softskill_ids:
                      type: array
                      items:
                        type: integer
                    tech_ids:
                      type: array
                      items:
                        type: integer
                  required:
                  - name
                  - email
                  - birthdate
                  - phone
                  - role
              required:
              - profile
            examples:
              Example:
                summary: Create a profile
                value:
                  profile:
                    name: Sabrina
                    email: sabrina@example.com
                    birthdate: '1991-07-27'
                    phone: '85988556677'
                    role: fullstack
                    bio: Uma desenvolvedora iniciante que está se dedicando para ser
                      fullstack. Atualmente trabalhando com Ruby on Rails.
                    links:
                    - https://github.com/sabrinagomesb
                    - https://www.linkedin.com/in/sabrina-gomes-bezerra/
                    city_id: '678'
                    experiences_attributes:
                    - title: Desenvolvedor Backend
                      company_name: RaroLabs
                      start_date: '2023-09-04'
                      function_performed: Desenvolver sistemas web com Ruby on Rails
                    - title: Estagiário de Desenvolvimento Web
                      company_name: WebTech
                      start_date: '2020-01-15'
                      end_date: '2020-12-31'
                      function_performed: Desenvolver com React
                    studies_attributes:
                    - title: Bacharelado em Ciência da Computação
                      institution: Raro Academy
                      link: www.raroacademy.com.br
                      start_date: '2022-08-01'
                    - title: Curso de Desenvolvimento Web Avançado
                      institution: Raro Academy
                      link: www.raroacademy.com.br
                      start_date: '2023-03-05'
                      end_date: '2023-06-12'
                    ability_ids:
                    - 1
                    - 3
                    softskill_ids:
                    - 1
                    - 2
                    - 3
                    tech_ids:
                    - 3
  "/abilities":
    get:
      summary: list abilities
      tags:
      - - Abilities
      parameters:
      - name: role
        in: query
        type: string
        description: Role filter
        schema:
          type: string
          enum:
          - frontend
          - backend
          - fullstack
          - mobile
          - designer
          - qa
        required: true
        example: frontend
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 2
                    name: Design de Interface de Usuário (UI)
                    role: fullstack
                    created_at: '2023-09-15T04:46:58.949Z'
                    updated_at: '2023-09-15T04:46:58.949Z'
                    description: Habilidade em criar interfaces de usuário atraentes
                      e funcionais.
  "/abilities/{id}":
    parameters:
    - name: id
      in: path
      required: true
    get:
      summary: show ability by id
      tags:
      - - Abilities
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 2
                    name: Design de Interface de Usuário (UI)
                    role: fullstack
                    created_at: '2023-09-15T04:46:58.949Z'
                    updated_at: '2023-09-15T04:46:58.949Z'
                    description: Habilidade em criar interfaces de usuário atraentes
                      e funcionais.
  "/profiles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show profile
      tags:
      - - Profiles
      responses:
        '200':
          description: successful
  "/profiles/{id}/download":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: download profile
      tags:
      - - Profiles
      responses:
        '200':
          description: successful
  "/softskills":
    get:
      summary: list softskills
      tags:
      - - Softskill
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 1
                    name: Comunicação
                    created_at: '2023-09-15T04:46:59.465Z'
                    updated_at: '2023-09-15T04:46:59.465Z'
  "/softskills/{id}":
    parameters:
    - name: id
      in: path
      required: true
    get:
      summary: show softskill
      tags:
      - - Softskill
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: Comunicação
                    created_at: '2023-09-15T04:46:59.465Z'
                    updated_at: '2023-09-15T04:46:59.465Z'
  "/states":
    get:
      summary: list states
      tags:
      - - State/City
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 6
                    name: Ceará
                    acronym: CE
                    created_at: '2023-09-15T04:47:03.198Z'
                    updated_at: '2023-09-15T04:47:03.198Z'
  "/states/{id}":
    parameters:
    - name: id
      in: path
      required: true
    get:
      summary: show state
      tags:
      - - State/City
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 6
                    name: Ceará
                    acronym: CE
                    created_at: '2023-09-15T04:47:03.198Z'
                    updated_at: '2023-09-15T04:47:03.198Z'
                    cities:
                    - id: 620
                      name: Abaiara
                      state_id: 6
                      created_at: '2023-09-15T04:47:03.202Z'
                      updated_at: '2023-09-15T04:47:03.202Z'
  "/states/{state_id}/cities":
    parameters:
    - name: state_id
      in: path
      required: true
    get:
      summary: list cities from state
      tags:
      - - State/City
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 678
                    name: Fortaleza
                    state_id: 6
                    created_at: '2023-09-15T04:47:03.524Z'
                    updated_at: '2023-09-15T04:47:03.524Z'
  "/states/{state_id}/cities/{id}":
    parameters:
    - name: state_id
      in: path
      required: true
    - name: id
      in: path
      required: true
    get:
      summary: show city from state
      tags:
      - - State/City
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 678
                    name: Fortaleza
                    state_id: 6
                    created_at: '2023-09-15T04:47:03.524Z'
                    updated_at: '2023-09-15T04:47:03.524Z'
  "/techs":
    get:
      summary: list techs
      tags:
      - - Techs
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 1
                    name: Ruby on Rails
                    created_at: '2023-09-15T04:46:58.560Z'
                    updated_at: '2023-09-15T04:46:58.560Z'
  "/techs/{id}":
    parameters:
    - name: id
      in: path
      required: true
    get:
      summary: show tech by id
      tags:
      - - Techs
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: Ruby on Rails
                    created_at: '2023-09-15T04:46:58.560Z'
                    updated_at: '2023-09-15T04:46:58.560Z'
servers:
- url: "{default}/"
  variables:
    default:
      default: localhost:3000
      description: render.com
