STACKS = [
  'Ruby on Rails',
  'React.js',
  'Node.js',
  'Python',
  'Java',
  'C#',
  'PHP',
  'Angular',
  'Vue.js',
  'Django',
  'Express.js',
  'Spring Boot',
  'Laravel',
  'Ruby',
  'Swift',
  'Kotlin',
  'JavaScript',
  'TypeScript',
  'HTML5',
  'CSS3',
  'SQL',
  'MongoDB',
  'MySQL',
  'PostgreSQL',
  'MariaDB',
  'SQLite',
  'Redis',
  'Git',
  'Docker',
  'AWS',
  'Azure',
  'Google Cloud',
  'React Native',
  'Flutter',
  'Vue.js',
  'RubyMotion',
  'Unity',
  'C++',
  'Rust',
  'Perl',
  'Scala',
  'Go',
  'R',
  'Elixir',
  'Haskell',
  'F#',
  'Matlab',
  'SAAS',
  '.NET',
  'C',
  'Assembly',
  'Next.js',
  'Nest.js',
  'Rest',
  'GraphQL',
  'Bootstrap',
  'Tailwind CSS',
  'Firebase'
]

FRONTEND_ABILITIES = [
  { name: 'Design de Interface de Usuário (UI)', description: 'Habilidade em criar interfaces de usuário atraentes e funcionais.' },
  { name: 'Design de Experiência do Usuário (UX)', description: 'Conhecimento em criar experiências de usuário intuitivas e eficientes.' },
  { name: 'Responsividade', description: 'Habilidade em criar designs responsivos que se adaptam a diferentes dispositivos e tamanhos de tela.' },
  { name: 'Acessibilidade', description: 'Conhecimento em tornar aplicações web acessíveis para pessoas com deficiência.' },
  { name: 'Performance', description: 'Otimização de carregamento de página e desempenho do frontend.' },
  { name: 'Testes de Frontend', description: 'Experiência em escrever testes automatizados para o frontend.' },
  { name: 'Controle de Versão', description: 'Habilidade em usar sistemas de controle de versão, como Git.' },
  { name: 'Pré-processadores CSS', description: 'Conhecimento em pré-processadores CSS, como SASS ou LESS.' },
  { name: 'Gerenciadores de Pacotes', description: 'Uso de ferramentas como npm ou Yarn para gerenciar dependências.' },
  { name: 'Boas Práticas de Codificação', description: 'Conhecimento em padrões e melhores práticas de codificação.' },
  { name: 'Ferramentas de Desenvolvimento', description: 'Familiaridade com ferramentas de desenvolvimento, como Chrome DevTools.' },
  { name: 'Colaboração', description: 'Capacidade de colaborar efetivamente com designers e desenvolvedores de backend.' },
  { name: 'Resolução de Problemas', description: 'Habilidade em solucionar problemas e depurar código frontend.' },
  { name: 'Conhecimento em SEO', description: 'Compreensão de otimização de mecanismos de busca para o frontend.' },
  { name: 'Versionamento de API', description: 'Conhecimento em trabalhar com APIs e versionamento.' },
  { name: 'Gerenciamento de Estado', description: 'Experiência em gerenciamento de estado de aplicativos, como Redux ou MobX.' },
  { name: 'Animações', description: 'Habilidade em criar animações e transições suaves no frontend.' }
]

BACKEND_ABILITIES = [
  { name: 'Desenvolvimento de APIs', description: 'Habilidade em criar APIs robustas e escaláveis.' },
  { name: 'Segurança de Dados', description: 'Conhecimento em práticas de segurança para proteger dados sensíveis.' },
  { name: 'Performance', description: 'Otimização de consultas e desempenho de banco de dados.' },
  { name: 'Gerenciamento de Banco de Dados', description: 'Experiência em bancos de dados relacionais ou NoSQL.' },
  { name: 'Controle de Versão', description: 'Habilidade em usar sistemas de controle de versão, como Git.' },
  { name: 'Testes de Backend', description: 'Experiência em escrever testes automatizados para o backend.' },
  { name: 'Princípios SOLID', description: 'Compreensão dos princípios SOLID de design de software.' },
  { name: 'Arquitetura de Software', description: 'Conhecimento em arquiteturas de software escaláveis.' },
  { name: 'Padrões de Projeto', description: 'Familiaridade com padrões de projeto de software.' },
  { name: 'Microserviços', description: 'Experiência em arquitetura de microserviços.' },
  { name: 'Mensageria', description: 'Uso de sistemas de mensagens para comunicação entre serviços.' },
  { name: 'Cache', description: 'Implementação de estratégias de cache para melhorar o desempenho.' },
  { name: 'Segurança Web', description: 'Conhecimento em proteção contra ameaças web, como SQL Injection e XSS.' },
  { name: 'Autenticação e Autorização', description: 'Implementação de sistemas de autenticação e autorização.' },
  { name: 'Documentação de API', description: 'Criação de documentação clara e completa para APIs.' },
  { name: 'Integração de Terceiros', description: 'Trabalho com integrações de APIs de terceiros.' },
  { name: 'Resolução de Problemas', description: 'Habilidade em solucionar problemas complexos de backend.' },
  { name: 'Escalabilidade', description: 'Design de sistemas que podem escalar horizontalmente.' }
]

MOBILE_ABILITIES = [
  { name: 'Desenvolvimento de Aplicativos iOS', description: 'Experiência em criar aplicativos para dispositivos iOS usando Swift ou Objective-C.' },
  { name: 'Desenvolvimento de Aplicativos Android', description: 'Habilidade em criar aplicativos Android usando Java ou Kotlin.' },
  { name: 'Design Responsivo para Dispositivos Móveis', description: 'Conhecimento em criar designs que se adaptem a diferentes tamanhos de tela em dispositivos móveis.' },
  { name: 'Desenvolvimento Cross-Platform', description: 'Experiência em criar aplicativos que funcionem em várias plataformas usando frameworks como Flutter ou React Native.' },
  { name: 'Integração de APIs Móveis', description: 'Conhecimento em trabalhar com APIs externas em aplicativos móveis.' },
  { name: 'Otimização de Desempenho Móvel', description: 'Experiência em otimizar o desempenho de aplicativos móveis para um carregamento mais rápido e uso eficiente de recursos.' },
  { name: 'Testes de Aplicativos Móveis', description: 'Capacidade de escrever testes automatizados para aplicativos móveis.' },
  { name: 'Segurança de Aplicativos Móveis', description: 'Conhecimento em práticas de segurança para proteger aplicativos móveis contra ameaças.' },
  { name: 'Publicação em Lojas de Aplicativos', description: 'Experiência em enviar aplicativos para a App Store da Apple e Google Play Store.' },
  { name: 'Interação com Hardware Móvel', description: 'Habilidade em acessar recursos de hardware em dispositivos móveis, como câmeras e sensores.' },
  { name: 'Notificações Push', description: 'Conhecimento em implementar notificações push em aplicativos móveis.' },
  { name: 'Controle de Versão', description: 'Uso de sistemas de controle de versão, como Git, para gerenciar o código-fonte do aplicativo móvel.' }
]

QA_ABILITIES = [
  { name: 'Testes de Software', description: 'Experiência em testar software para identificar bugs e problemas.' },
  { name: 'Testes de Regressão', description: 'Capacidade de executar testes de regressão para garantir que as alterações não quebrem funcionalidades existentes.' },
  { name: 'Testes Funcionais', description: 'Conhecimento em realizar testes funcionais para verificar se o software atende aos requisitos.' },
  { name: 'Automação de Testes', description: 'Experiência em automatizar testes para aumentar a eficiência e a cobertura de testes.' },
  { name: 'Testes de Aceitação do Usuário', description: 'Habilidade em conduzir testes de aceitação do usuário para validar se o software atende às necessidades do usuário final.' },
  { name: 'Testes de Desempenho', description: 'Conhecimento em realizar testes de desempenho para avaliar a velocidade e a eficiência do software.' },
  { name: 'Relatórios de Defeitos', description: 'Capacidade de relatar e documentar defeitos encontrados durante os testes.' },
  { name: 'Testes de Segurança', description: 'Experiência em realizar testes de segurança para identificar vulnerabilidades no software.' },
  { name: 'Testes Exploratórios', description: 'Habilidade em realizar testes exploratórios para descobrir problemas não documentados.' },
  { name: 'Ferramentas de Teste', description: 'Conhecimento em usar ferramentas de teste, como Selenium, JIRA, ou similares.' },
  { name: 'Metodologias de Teste', description: 'Experiência em seguir metodologias de teste, como Agile ou Scrum.' },
  { name: 'Controle de Qualidade', description: 'Uso de práticas de controle de qualidade para garantir a entrega de software de alta qualidade.' }
]

DESIGNER_ABILITIES = [
  { name: 'Design Gráfico', description: 'Habilidade em criar designs gráficos para impressão e mídia digital.' },
  { name: 'UI/UX Design', description: 'Experiência em design de interface do usuário (UI) e experiência do usuário (UX) para aplicativos e websites.' },
  { name: 'Ilustração Digital', description: 'Capacidade de criar ilustrações digitais usando ferramentas como Adobe Illustrator ou Procreate.' },
  { name: 'Edição de Imagens', description: 'Conhecimento em edição de imagens usando softwares como Adobe Photoshop ou GIMP.' },
  { name: 'Design de Logotipos', description: 'Experiência em criar logotipos e identidade visual de marcas.' },
  { name: 'Web Design Responsivo', description: 'Habilidade em criar designs web que se adaptam a diferentes dispositivos e tamanhos de tela.' },
  { name: 'Tipografia', description: 'Conhecimento em seleção e uso adequado de tipografia em designs.' },
  { name: 'Design de Interface de Aplicativos', description: 'Capacidade de criar interfaces de usuário atraentes e funcionais para aplicativos.' },
  { name: 'Ilustração Vetorial', description: 'Experiência em criar ilustrações vetoriais escaláveis.' },
  { name: 'Design de Embalagens', description: 'Habilidade em criar designs de embalagens para produtos.' },
  { name: 'Design de Experiência do Usuário (UX)', description: 'Experiência em melhorar a experiência geral do usuário em produtos e serviços.' },
  { name: 'Design de Material de Marketing', description: 'Capacidade de criar material de marketing, como panfletos e brochuras.' },
  { name: 'Arte Conceitual', description: 'Conhecimento em criar arte conceitual para jogos e mídia interativa.' },
  { name: 'Design de Personagens', description: 'Experiência em criar personagens e figurinos para jogos e animações.' },
  { name: 'Ferramentas de Design', description: 'Uso de ferramentas de design, como Adobe Creative Cloud, Sketch, Figma, etc.' }
]
