STACKS = [
  'Ruby on Rails',
  'React.js',
  'Node.js',
  'Python',
  'Java',
  'C#',
  'PHP',
  'Angular',
  'Vue.js',
  'Django',
  'Express.js',
  'Spring Boot',
  'Laravel',
  'Ruby',
  'Swift',
  'Kotlin',
  'JavaScript',
  'TypeScript',
  'HTML5',
  'CSS3',
  'SQL',
  'MongoDB',
  'MySQL',
  'PostgreSQL',
  'MariaDB',
  'SQLite',
  'Redis',
  'Git',
  'Docker',
  'AWS',
  'Azure',
  'Google Cloud',
  'React Native',
  'Flutter',
  'Vue.js',
  'RubyMotion',
  'Unity',
  'C++',
  'Rust',
  'Perl',
  'Scala',
  'Go',
  'R',
  'Elixir',
  'Haskell',
  'F#',
  'Matlab',
  'SAAS',
  '.NET',
  'C',
  'Assembly',
  'Next.js',
  'Nest.js',
  'Rest',
  'GraphQL',
  'Bootstrap',
  'Tailwind CSS',
  'Firebase'
]

FRONTEND_ABILITIES = [
  { name: 'Design de Interface de Usuário (UI)', description: 'Habilidade em criar interfaces de usuário atraentes e funcionais.' },
  { name: 'Design de Experiência do Usuário (UX)', description: 'Conhecimento em criar experiências de usuário intuitivas e eficientes.' },
  { name: 'Responsividade', description: 'Habilidade em criar designs responsivos que se adaptam a diferentes dispositivos e tamanhos de tela.' },
  { name: 'Acessibilidade', description: 'Conhecimento em tornar aplicações web acessíveis para pessoas com deficiência.' },
  { name: 'Performance', description: 'Otimização de carregamento de página e desempenho do frontend.' },
  { name: 'Testes de Frontend', description: 'Experiência em escrever testes automatizados para o frontend.' },
  { name: 'Controle de Versão', description: 'Habilidade em usar sistemas de controle de versão, como Git.' },
  { name: 'Pré-processadores CSS', description: 'Conhecimento em pré-processadores CSS, como SASS ou LESS.' },
  { name: 'Gerenciadores de Pacotes', description: 'Uso de ferramentas como npm ou Yarn para gerenciar dependências.' },
  { name: 'Boas Práticas de Codificação', description: 'Conhecimento em padrões e melhores práticas de codificação.' },
  { name: 'Ferramentas de Desenvolvimento', description: 'Familiaridade com ferramentas de desenvolvimento, como Chrome DevTools.' },
  { name: 'Colaboração', description: 'Capacidade de colaborar efetivamente com designers e desenvolvedores de backend.' },
  { name: 'Resolução de Problemas', description: 'Habilidade em solucionar problemas e depurar código frontend.' },
  { name: 'Conhecimento em SEO', description: 'Compreensão de otimização de mecanismos de busca para o frontend.' },
  { name: 'Versionamento de API', description: 'Conhecimento em trabalhar com APIs e versionamento.' },
  { name: 'Gerenciamento de Estado', description: 'Experiência em gerenciamento de estado de aplicativos, como Redux ou MobX.' },
  { name: 'Animações', description: 'Habilidade em criar animações e transições suaves no frontend.' }
]
